apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy1
spec:
  selector:
    matchLabels:
      app: nginx-deploy1
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-deploy1
    spec:
      containers:
      - name: nginx-pod1
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deploy1
spec:
  type: LoadBalancer
  selector:
    app: nginx-deploy1
  ports:
  - port: 80
    targetPort: 80
    nodePort: 0
